### ISSUE TITLE
Ödev template

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/Group_Homeworks#6]
Odevimiz için döküman templateini oluşturdum. Bu döküman üzerinde ekleme yapabilirsiniz. Yaptığınız eklemeler için (varsa)özellikle makalelerde referans da eklemenizi rica edeceğim referans kısmına. Linki paylaşıyorum. Sorunuz olursa konusalım.
https://docs.google.com/document/d/1smNzHYrEvblVV1zlzPYJiVlHR4bXB5pi/edit?usp=sharing&ouid=115995519446981806990&rtpof=true&sd=true

**Comment by samozturk** [comment]
1. soruya aciklamalar ekledim.
